# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout somewhen, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# font for window titles. ISO 10646 = Unicode
font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec mate-terminal --hide-menubar

# kill focused window
bindsym $mod+c kill

# start dmenu (a program launcher)
bindsym $mod+e exec dmenu_run 

# change focus
bindsym $mod+h focus left
bindsym $mod+n focus down
bindsym $mod+t focus up
bindsym $mod+s focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+H move left
bindsym $mod+Shift+N move down
bindsym $mod+Shift+T move up
bindsym $mod+Shift+S move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+d split h

# split in vertical orientation
bindsym $mod+k split v

# enter fullscreen mode for the focused container
#bindsym $mod+u fullscreen

# change container layout (stacked, tabbed, default)
#bindsym $mod+o layout stacking
#bindsym $mod+comma layout tabbed
bindsym $mod+period layout default

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindcode 74 exec guake -e "i3lock && systemctl suspend"

# focus the child container
#bindcode $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace "1: Email"
bindsym $mod+2 workspace "2: Music"
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace "8: Dev"
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace "10: Internet"
bindsym $mod+apostrophe workspace 11
bindsym $mod+comma workspace 12
bindsym $mod+l workspace 13

# move focused container to workspace
bindsym $mod+Shift+exclam move container to workspace "1: Email"
bindsym $mod+Shift+at move container to workspace "2: Music"
bindsym $mod+Shift+numbersign move container to workspace 3
bindsym $mod+Shift+dollar move container to workspace 4
bindsym $mod+Shift+percent move container to workspace 5
bindsym $mod+Shift+asciicircum move container to workspace 6
bindsym $mod+Shift+ampersand move container to workspace 7
bindsym $mod+Shift+asterisk move container to workspace "8: Dev"
bindsym $mod+Shift+parenleft move container to workspace 9
bindsym $mod+Shift+parenright move container to workspace "10: Internet"
bindsym $mod+Shift+quotedbl move container to workspace 11
bindsym $mod+Shift+less move container to workspace 12
bindsym $mod+Shift+L move container to workspace 13

# reload the configuration file
bindsym $mod+Shift+J reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+P restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+greater exit

# resize window (you can also use the mouse for that)
mode "resize" {
# These bindings trigger as soon as you enter the resize mode

# Pressing left will shrink the window’s width.
# Pressing right will grow the window’s width.
# Pressing up will shrink the window’s height.
# Pressing down will grow the window’s height.
	bindsym h resize shrink width 10 px or 10 ppt
		bindsym n resize grow height 10 px or 10 ppt
		bindsym t resize shrink height 10 px or 10 ppt
		bindsym s resize grow width 10 px or 10 ppt

# same bindings, but for the arrow keys
		bindsym 113 resize shrink width 10 px or 10 ppt
		bindsym 116 resize grow height 10 px or 10 ppt
		bindsym 111 resize shrink height 10 px or 10 ppt
		bindsym 114 resize grow width 10 px or 10 ppt

# back to normal: Enter or Escape
		bindsym Return mode "default"
		bindsym Escape mode "default"
}

bindsym $mod+p mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
	status_command i3status
		colors
		{
			statusline #ffffff
				background #323232



				focused_workspace #30273c #ffffff #323232
				active_workspace #30273c #ffffff #323232
				inactive_workspace #30273c #323232 #ffffff
				urgent_workspace #2f343a #900000 #ffffff
		}

	position top

}
exec firefox
exec guake -e "/home/brendan/schleep.sh &"
exec_always xfce4-power-manager
exec_always mate-settings-daemon
exec nm-applet
new_window 1pixel
bindsym $mod+r exec --no-startup-id xdotool mousemove 1356 5
bindsym $mod+m bar mode toggle
bindsym $mod+u exec --no-startup-id xdotool click 1
bindsym $mod+g exec --no-startup-id xdotool mousemove 100 760
bindsym $mod+x move workspace to output right
exec_always xrandr --output VGA1 --auto --left-of LVDS1
exec_always xrandr --output LVDS1 --mode 1366x768
exec mate-terminal -e mutt --hide-menubar


#the 30273c is what the background used to be prior to deletion
client.focused #323232 #323232 #323232 #323232
client.focused_inactive #0000ff #0000ff #0000ff #0000ff
client.unfocused #0000ff #0000ff #0000ff #0000ff
client.urgent #0000ff #0000ff #0000ff #0000ff
